USE [ECARGOROSA]
GO
/****** Object:  StoredProcedure [dbo].[SP_040_EPOD_SAMGUNG_GRA_COMP_ENTREGA02]    Script Date: 02/03/2023 15:13:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
 
 

CREATE ProcEDURE [dbo].[SP_040_EPOD_SAMGUNG_GRA_COMP_ENTREGA02] /*  SP_040_EPOD_SAMGUNG_GRA_COMP_ENTREGA02.SQL */
	@LISTA_TRACK_ID VARCHAR(7999)

AS
	DECLARE 
		@PARAM_CAMINHO_ARQUIVO VARCHAR(500),
		@NOME_ARQUIVO	VARCHAR(255),
		@EXTENSAO		VARCHAR(10),
		@Num_Pedido		varchar(50),
		@DATA_TRACKING	DATETIME,
		@Nome_Imagem	varchar(100),
		@Imagem			varbinary(MAX),
		@CAMINHO_COMPLETO VARCHAR(1000),
		@ObjectToken	INT,
		@POSICAO_PONTO	INT,
		@MSG_RET		VARCHAR(255) = '',
		@RETORNO		INT = 0

	SELECT @PARAM_CAMINHO_ARQUIVO = PARAMETRO FROM TAB_PARAMETRO_SISTEMA WHERE TAB_PARAMETRO_SISTEMA_ID = 8705

	IF ISNULL(@PARAM_CAMINHO_ARQUIVO, '') = ''
		GOTO FINAL
		
	CREATE TABLE #TEMP_TRACKING_IDS (
		TRACKING_ID INT NULL
    )

	CREATE TABLE #TEMP_NOTAS (
		NOTA_FISCAL_ID INT NULL,
		Num_Pedido varchar(50) Null,
		DATA_TRACKING datetime null,
		Nome_Imagem varchar(100) Null,
		Imagem varbinary(max) null
	)


	

	IF RIGHT(@PARAM_CAMINHO_ARQUIVO,1) <> '\' AND RIGHT(@PARAM_CAMINHO_ARQUIVO,1) <> '/'
		SET @PARAM_CAMINHO_ARQUIVO += '\' 

	BEGIN TRY 
		EXEC SP_CreateFolder @PARAM_CAMINHO_ARQUIVO
	END TRY
	BEGIN CATCH
		SET @RETORNO = 10
		SET @MSG_RET = 'Não foi possível acessar o caminho ' + @PARAM_CAMINHO_ARQUIVO + '. Verifique o parâmetro 8705.'
		GOTO FINAL
	END CATCH

	INSERT INTO #TEMP_TRACKING_IDS (TRACKING_ID)
	SELECT * FROM Fn_split(@LISTA_TRACK_ID, '#')

	insert INTO #TEMP_NOTAS
    SELECT DISTINCT NOTA_FISCAL.NOTA_FISCAL_ID, NOTA_FISCAL.NUM_PEDIDO, TRACKING.DATA_TRACKING, IMG_DOCTO.Nome_Imagem, IMG_DOCTO.IMAGEM
    FROM NOTA_FISCAL (nolock)
    INNER JOIN TRACKING (nolock) ON NOTA_FISCAL.DOCTO_TRANSPORTE_ID = TRACKING.DOCTO_TRANSPORTE_ID Or NOTA_FISCAL.Nota_Fiscal_ID = TRACKING.Nota_Fiscal_Id
    INNER JOIN #TEMP_TRACKING_IDS (nolock) ON TRACKING.TRACKING_ID = #TEMP_TRACKING_IDS.TRACKING_ID
    INNER JOIN DOCTO_IMG (nolock) ON DOCTO_IMG.NOTA_FISCAL_ID = NOTA_FISCAL.NOTA_FISCAL_ID AND ISNULL(DOCTO_IMG.TAB_STATUS_ID,1) <> 2
    INNER JOIN IMG_DOCTO (nolock) ON DOCTO_IMG.IMG_DOCTO_ID = IMG_DOCTO.IMG_DOCTO_ID
    INNER JOIN Tab_tipo_TRACKING (nolock) ON Tab_tipo_TRACKING.Tab_tipo_TRACKING_ID = TRACKING.Tab_tipo_TRACKING_ID and Tab_tipo_TRACKING.Indic_Entrega = 'S'
    WHERE NOTA_FISCAL.TAB_STATUS_ID <> 2 

	--select * from #TEMP_NOTAS
	IF EXISTS (SELECT NOTA_FISCAL_ID FROM #TEMP_NOTAS)
		BEGIN 
			DECLARE CURSOR_IMG CURSOR FAST_FORWARD FOR 
				SELECT DISTINCT Num_Pedido,
					DATA_TRACKING,
					Nome_Imagem,
					Imagem
				from #TEMP_NOTAS
			OPEN CURSOR_IMG 

			FETCH NEXT FROM CURSOR_IMG INTO @Num_Pedido, @DATA_TRACKING, @Nome_Imagem, @Imagem 

			WHILE @@FETCH_STATUS = 0
				BEGIN
					SET @POSICAO_PONTO = 0
					SET @EXTENSAO = NULL
					SET @CAMINHO_COMPLETO = NULL

					SET @EXTENSAO = RIGHT(@Nome_Imagem, 5)
					SET @POSICAO_PONTO = CHARINDEX('.', @EXTENSAO)

					IF ISNULL(@POSICAO_PONTO,0) > 0
						SET @EXTENSAO = RIGHT(@EXTENSAO, LEN(@EXTENSAO) - @POSICAO_PONTO + 1)
					ELSE
						SET @EXTENSAO = NULL		
						
					SET @Nome_Imagem = LTRIM(RTRIM(REPLACE(@Nome_Imagem, @EXTENSAO, '')	))
					
					SET @CAMINHO_COMPLETO = @PARAM_CAMINHO_ARQUIVO + ISNULL(UPPER(@Num_Pedido),'') + '_' + replace(convert(varchar,@DATA_TRACKING,103),'/','')  + '.JPG'

					PRINT @CAMINHO_COMPLETO

					EXEC sp_OACreate 'ADODB.Stream', @ObjectToken OUTPUT
					EXEC sp_OASetProperty @ObjectToken, 'Type', 1
					EXEC sp_OAMethod @ObjectToken, 'Open'
					EXEC sp_OAMethod @ObjectToken, 'Write', NULL, @Imagem
					EXEC sp_OAMethod @ObjectToken, 'SaveToFile', NULL, @CAMINHO_COMPLETO, 2
					EXEC sp_OAMethod @ObjectToken, 'Close'
					EXEC sp_OADestroy @ObjectToken

					FETCH NEXT FROM CURSOR_IMG INTO @Num_Pedido, @DATA_TRACKING, @Nome_Imagem, @Imagem 
				END 

			CLOSE CURSOR_IMG
			DEALLOCATE CURSOR_IMG
		END

FINAL:

	DROP TABLE #TEMP_TRACKING_IDS
	DROP TABLE #TEMP_NOTAS

	SELECT @RETORNO RETORNO, @MSG_RET MSG_RET
 
